name: "Infrastructure Sync"

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.8

      - name: OpenTofu fmt
        run: tofu fmt -check
        continue-on-error: true

      - name: OpenTofu Init
        run: tofu init

      - name: OpenTofu Validate
        run: tofu validate -no-color

      - name: OpenTofu Plan
        run: tofu plan -no-color
        continue-on-error: true
